apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"challenge":true,"htpasswd":{"fileData":{"name":"htpasswd-secret"}},"login":true,"mappingMethod":"claim","name":"htpasswd_provider","type":"HTPasswd"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-03-05T20:01:00Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 00d0759a-42b8-4292-814d-60e8ba2fd1e9
  resourceVersion: "325149"
  uid: ab10172d-b281-41cc-9fef-4d1f908a44db
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=admin,cn=users,cn=accounts,dc=ocp4,dc=example,dc=com
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldap://idm.ocp4.example.com/cn=users,cn=accounts,dc=ocp4,dc=example,dc=com?uid
    mappingMethod: claim
    name: Red Hat Identity Management
    type: LDAP
  - htpasswd:
      fileData:
        name: secret-sre-team
    mappingMethod: claim
    name: idp-htpasswd-sre-team
    type: HTPasswd
  - htpasswd:
      fileData:
        name: secret-devops-team
    mappingMethod: claim
    name: idp-htpasswd-devops-team
    type: HTPasswd
  - htpasswd:
      fileData:
        name: secret-myapp-team
    mappingMethod: claim
    name: idp-htpasswd-myapp-team
    type: HTPasswd
