apiVersion: v1
data:
  htpasswd: dXNlcjExOiQyeSQwNSRpcEtOZnRPVEY2NTFNQ2N0M1dQOEVPTkJDRnZiNVkxd0VWZUl3VXFZaHlTMXoubk43eDM1Ngp1c2VyMTI6JDJ5JDA1JG01MUMudG56b3lVVEtQczRGQ2lxWC5aUXF6N3V0MFJsd1RzM0NydkdYQk9OMEJuY011SFpXCnVzZXIxMzokMnkkMDUkYUVpOFpNYWFGMWJvcncvcHZyMUwzT1lOT0hpWmtGSDdXMFFsbVl5R1dtTDNWVk1JVXRFbTIKdXNlcjE0OiQyeSQwNSRxVHdHN2dTYXgzVVQ0M1ZIQUZYWkllSmxvWnFHYS50MFFRM1NPOWpZZUc0SHRDdmJWakQ4Ngp1c2VyMTU6JDJ5JDA1JHBZSFlFZkF2WVEvb09zdmE2aEF0SE84RUNiei92dnVzdXJUUXoxQ3RFdTVlak9XdXNqOW0yCnVzZXIxNjokMnkkMDUkTHRISzZtR0RrYS5MSE9KSG5CYlJmT2o3V0U5RVQ3Y1dKRmZiT1ZDMjJhRzhhbVFjUFFYUnUKdXNlcjE3OiQyeSQwNSRoRGRFVnJ1OGg0ZHBpVkFaaFAzSlpPdlN3cXJmazE2UzNhRGw3NzRCNTJZOFhWYVBmQTAzbQp1c2VyMTg6JDJ5JDA1JG5Yd3JybWdZQXRETTNiMDFYWkRXWHVmVkZ0bjZZakxtajNXT0wyOWNlUFJadERZNldtMjVxCnVzZXIxOTokMnkkMDUkMHR2bUw3Ymh1MDNEalVrYXE0a0ZMZXJaWUpvYk1QYjJTVHhGZ1NaNGJrcy5pTUhWRVc3d08KdXNlcjIwOiQyeSQwNSRucGRNME10QXlyeWxmckpEM3VIdUJPbmY3dEE5MkVTUXNrSjR6d0NqM0JGRVpYV0hLa216YQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-devops-team
  namespace: openshift-config
